name: Flyway – demodb.myschema

on:
  push:
    paths-ignore:
    - '.github/**'
    - 'migrations/demodb/another_schema/**'
    - 'README.md'
    - 'docs/**'
    branches:
      - develop
      - release
      - master

  workflow_dispatch:
    inputs:
      target_branch:
        description: "Target environment"
        required: true
        type: choice
        options:
          - dev
          - qa
          - prod
      flyway_command:
        description: "Flyway command"
        required: true
        default: migrate
        type: choice
        options:
          - migrate
          - validate
          - info
          - baseline
      baseline_version:
        description: "Baseline version (ONLY when command=baseline)"
        required: false
        default: "1"

jobs:
  flyway:
    runs-on: ${{ 
      (
        (github.event_name == 'workflow_dispatch' && inputs.target_branch == 'prod')
        || github.ref_name == 'master'
      )
      && fromJSON('["self-hosted","prod"]')
      || fromJSON('["self-hosted","dev"]')
      }}


    # Resolve environment from branch
    environment: >
      ${{ github.event_name == 'workflow_dispatch' && inputs.target_branch == 'dev' && 'dev' ||
         github.event_name == 'workflow_dispatch' && inputs.target_branch == 'qa' && 'qa' ||
         github.event_name == 'workflow_dispatch' && inputs.target_branch == 'prod' && 'prod' ||
         github.ref_name == 'develop' && 'dev' ||
         github.ref_name == 'release' && 'qa' ||
         github.ref_name == 'master' && 'prod' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: >
            ${{ github.event_name == 'workflow_dispatch' && inputs.target_branch == 'dev' && 'develop' ||
               github.event_name == 'workflow_dispatch' && inputs.target_branch == 'qa' && 'release' ||
               github.event_name == 'workflow_dispatch' && inputs.target_branch == 'prod' && 'master' ||
               github.ref }}

      - name: Run Flyway CLI on demodb.myschema
        run: |
          # Resolve the command
          FLYWAY_CMD="${{ github.event_name == 'workflow_dispatch' && inputs.flyway_command || 'migrate' }}"

          # Include baseline version only if baseline
          if [ "$FLYWAY_CMD" = "baseline" ]; then
            BASELINE_OPTION="-baselineVersion=${{ github.event_name == 'workflow_dispatch' && inputs.baseline_version || '1' }}"
          else
            BASELINE_OPTION=""
          fi

          # Run Flyway
          flyway \
            -url=jdbc:postgresql://${{ secrets.DB_HOST }}:5432/qrdb \
            -user=${{ secrets.DB_USER }} \
            -password=${{ secrets.DB_PASSWORD }} \
            -schemas=myschema \
            -defaultSchema=myschema \
            -locations=filesystem:migrations/demodb/myschema \
            $FLYWAY_CMD \
            $BASELINE_OPTION
